# -*- coding: utf-8 -*-
"""0518 AI 模擬生成器.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDCNLZK8iTqDyZJ8ADdqQCrtn5UC1a_0
"""


import fitz  # PyMuPDF
from flask import Flask, request, render_template
import fitz  # pymupdf
import os
from openai import OpenAI

app = Flask(__name__)

# Load OpenAI key from env
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/upload', methods=['POST'])
def upload():
    pdf_file = request.files['pdf']
    text = ""
    with fitz.open(stream=pdf_file.read(), filetype="pdf") as doc:
        for page in doc:
            text += page.get_text()

    # Generate MCQs with OpenAI here...
    # response = client.chat.completions.create(...) etc.

    return f"<pre>{text[:1000]}</pre>"  # For now, just preview text

import os

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))


# Upload PDF
uploaded = files.upload()

# Extract Traditional Chinese text
pdf_text = ""
for filename in uploaded:
    with fitz.open(filename) as doc:
        for page in doc:
            pdf_text += page.get_text()

# Optional: truncate to stay within token limit
input_text = pdf_text[:3000]

import os
from openai import OpenAI

client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))


prompt = f"""
根據以下繁體中文內容，請生成三題選擇題，每題包含以下格式，並以繁體中文回答：

---
問題：<你的問題>
A：<選項A>
B：<選項B>
C：<選項C>
D：<選項D>
答案：<正確選項（僅填 A、B、C 或 D）>
---

請務必使用上述格式，不要加入多餘的說明或標題。

以下是內容：
{input_text}
"""

response = client.chat.completions.create(
    model="gpt-4",
    messages=[{"role": "user", "content": prompt}],
    temperature=0.7,
)

generated_text = response.choices[0].message.content
print("📝 GPT 回傳內容：\n", generated_text)

# --- Parse into structured MCQs ---
def parse_mcqs(text):
    questions = []
    blocks = text.strip().split("\n\n")
    for block in blocks:
        lines = block.strip().split("\n")
        q = {}
        for line in lines:
            if line.startswith("問題："):
                q["問題"] = line.replace("問題：", "").strip()
            elif line.startswith("A："):
                q["A"] = line.replace("A：", "").strip()
            elif line.startswith("B："):
                q["B"] = line.replace("B：", "").strip()
            elif line.startswith("C："):
                q["C"] = line.replace("C：", "").strip()
            elif line.startswith("D："):
                q["D"] = line.replace("D：", "").strip()
            elif line.startswith("答案："):
                q["答案"] = line.replace("答案：", "").strip()
        if len(q) == 6:
            questions.append(q)
    return questions

questions = parse_mcqs(generated_text)

import json
import os
import gspread
from google.oauth2.service_account import Credentials

SCOPES = ["https://www.googleapis.com/auth/spreadsheets"]

# Load credentials from env variable
service_account_info = json.loads(os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON"))
creds = Credentials.from_service_account_info(service_account_info, scopes=SCOPES)

gc = gspread.authorize(creds)



# Open your Google Spreadsheet
sheet = gc.open('問題生成器').sheet1  # Must exist

# Write questions
start_row = 2
for i, q in enumerate(questions):
    row = start_row + i
    row_data = [
        q["問題"],
        q["A"],
        q["B"],
        q["C"],
        q["D"],
        q["答案"]
    ]
    sheet.update(f"A{row}:F{row}", [row_data])

print("✅ 已成功寫入 Google 試算表")
